import React from 'react';
import { AlertTriangle, FileText, CheckCircle, CreditCard, RefreshCw } from 'lucide-react';

const TermsPage: React.FC = () => {
  return (
    <div className="animate-in fade-in duration-500 max-w-4xl mx-auto pb-12">
      <div className="text-center mb-12">
        <h1 className="text-3xl md:text-4xl font-extrabold text-slate-900 mb-4">Terms of Service</h1>
        <p className="text-slate-500">Effective Date: October 2023</p>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-8 md:p-12 space-y-10">
        
        {/* Critical Disclaimer */}
        <div className="bg-red-50 border-l-4 border-red-500 p-6 rounded-r-xl">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-6 h-6 text-red-600 shrink-0 mt-1" />
            <div>
              <h3 className="font-bold text-red-900 mb-2">Accuracy Disclaimer</h3>
              <p className="text-red-800 text-sm leading-relaxed">
                SocialPulse Lite provides <strong>estimations</strong> based on public metrics and industry-standard algorithms. We do not use private APIs from YouTube, Instagram, or TikTok to fetch hidden data. 
                <br/><br/>
                Growth projections and earnings estimates are hypothetical and not guaranteed. You should not make financial decisions solely based on these tools.
              </p>
            </div>
          </div>
        </div>

        {/* 1. Services */}
        <section>
          <div className="flex items-center gap-3 mb-4">
            <FileText className="w-6 h-6 text-slate-900" />
            <h2 className="text-xl font-bold text-slate-900">1. Scope of Service</h2>
          </div>
          <p className="text-slate-600 leading-relaxed mb-4">
            SocialPulse Lite offers a suite of web-based analytics calculators.
          </p>
          <ul className="space-y-2 text-slate-600 list-disc ml-5">
            <li><strong>Free Tier:</strong> Access to basic calculators with ad-support. No account required.</li>
            <li><strong>Pro Tier:</strong> Access to advanced trends, PDF exports, and ad-free usage. Requires a paid subscription.</li>
          </ul>
        </section>

        {/* 2. Subscription & Billing */}
        <section>
          <div className="flex items-center gap-3 mb-4">
            <CreditCard className="w-6 h-6 text-slate-900" />
            <h2 className="text-xl font-bold text-slate-900">2. Subscription & Billing</h2>
          </div>
          <div className="bg-slate-50 p-6 rounded-xl border border-slate-100 space-y-4">
            <div>
              <h3 className="font-bold text-slate-900 text-sm uppercase tracking-wide mb-1">Pricing</h3>
              <p className="text-slate-600 text-sm">
                The Pro plan is billed at <strong>$49.00 USD per month</strong>. You may also select multi-month packages at checkout.
              </p>
            </div>
            <div>
              <h3 className="font-bold text-slate-900 text-sm uppercase tracking-wide mb-1">Billing Cycle</h3>
              <p className="text-slate-600 text-sm">
                Payments are collected in advance. Your subscription will automatically renew at the end of each billing cycle unless cancelled.
              </p>
            </div>
            <div>
              <h3 className="font-bold text-slate-900 text-sm uppercase tracking-wide mb-1">Cancellation</h3>
              <p className="text-slate-600 text-sm">
                You may cancel your subscription at any time via your dashboard. Upon cancellation, you will retain Pro access until the end of your current paid period. We do not offer refunds for partial months used.
              </p>
            </div>
          </div>
        </section>

        {/* 3. Intellectual Property */}
        <section>
          <div className="flex items-center gap-3 mb-4">
            <CheckCircle className="w-6 h-6 text-slate-900" />
            <h2 className="text-xl font-bold text-slate-900">3. Intellectual Property</h2>
          </div>
          <p className="text-slate-600 leading-relaxed">
            The reports generated by SocialPulse Lite (PDFs/CSVs) are yours to own and share with brands or agencies. However, the underlying software, design, and algorithms remain the property of SocialPulse Lite. You may not reverse-engineer or scrape our tools.
          </p>
        </section>

        {/* 4. Limitation of Liability */}
        <section>
           <h2 className="text-xl font-bold text-slate-900 mb-4">4. Limitation of Liability</h2>
           <p className="text-slate-600 leading-relaxed">
             SocialPulse Lite is provided "as is". We are not liable for any damages arising from the use or inability to use our services, including but not limited to loss of profits, data, or goodwill. We do not guarantee 100% uptime.
           </p>
        </section>

        {/* 5. Platform Affiliation */}
        <section className="border-t border-gray-100 pt-6">
           <h2 className="text-lg font-bold text-slate-900 mb-2">5. Platform Disclaimer</h2>
           <p className="text-slate-500 text-sm leading-relaxed">
             We are <strong>not affiliated</strong> with Instagram, Facebook (Meta), YouTube (Google), or TikTok (ByteDance). All trademarks belong to their respective owners. We use the names of these platforms solely for descriptive purposes to indicate compatibility of our analytics tools.
           </p>
        </section>

      </div>
    </div>
  );
};

export default TermsPage;